/**
 * Clean out directory before bundling.
 * Removes stale JS/map files generated by tsc watch mode.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outDir = path.join(__dirname, '..', 'out');

if (fs.existsSync(outDir)) {
  fs.rmSync(outDir, { recursive: true, force: true });
  console.log(`Cleaned: ${outDir}`);
} else {
  console.log(`Already clean: ${outDir}`);
}
